In [0]:
import tensorflow as tf

In [0]:
a = tf.placeholder(tf.float64, name='a')
na = tf.placeholder(tf.float64, name='na')
b = tf.placeholder(tf.float64, name='b')
nb = tf.placeholder(tf.float64, name='nb')
c = tf.placeholder(tf.float64, name='c')
#aa = tf.multiply(na, a, name='aa')
aa = na * a
#bb = tf.multiply(nb, b, name='bb')
bb = nb * b
#aabb = tf.add(aa, bb, name='aabb')
aabb = aa + bb
#caabb = tf.multiply(c, aabb, name='caabb')
caabb = c * aabb

In [0]:
ga, gna, gb, gnb, gaa, gbb, gaabb, gc, gcaabb = tf.gradients(caabb, [a, na, b, nb, aa, bb, aabb, c, caabb])

In [0]:
feed_dict = {a: 100, na: 2, b: 150, nb: 3, c: 1.1}

In [5]:
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  v_caabb = sess.run(caabb, feed_dict)
  print(v_caabb)
  grads = sess.run([ga, gna, gb, gnb, gaa, gbb, gaabb, gc, gcaabb], feed_dict)
  print(grads)

715.0000000000001
[2.2, 110.00000000000001, 3.3000000000000003, 165.0, 1.1, 1.1, 1.1, 650.0, 1.0]


In [0]:
m = 2
x = tf.placeholder(tf.float64, shape=(m,1), name='x')
n = tf.placeholder(tf.float64, shape=(m,1), name='n')
c = tf.placeholder(tf.float64, name='c')
xn = tf.matmul(x, n, transpose_a=True, name='xn')
#caabb = tf.multiply(c, aabb, name='caabb')
cxn = c * xn

In [0]:
g = tf.gradients(cxn, [x, n, c])

In [0]:
feed_dict = {x: [[100], [150]], n: [[2], [3]], c: 1.1}

In [9]:
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  v_cxn = sess.run(cxn, feed_dict)
  print(type(v_cxn))
  print(v_cxn)
  grads = sess.run(g, feed_dict)
  #print(type(grads[0]))
  #print(grads[0])
  #print(grads[1])
  #print(grads[2])
  print(grads)

<type 'numpy.ndarray'>
[[715.]]
[array([[2.2],
       [3.3]]), array([[110.],
       [165.]]), 650.0]


Soft thresholding

In [0]:
def soft_thresholding(r_, lam_):
    "implement a soft threshold function y=sign(r)*max(0,abs(r)-lam)"
    lam_ = tf.maximum(lam_, 0)
    return tf.sign(r_) * tf.maximum(tf.abs(r_) - lam_, 0)

In [0]:
z = tf.placeholder(tf.float64, name='z')
th = tf.placeholder(tf.float64, name='th')
soft_z = soft_thresholding(z, th)
g = tf.gradients(soft_z, [z, th])

In [13]:
import numpy as np
feed_dict = {z: np.linspace(-3., 3., 21, dtype=np.float64), th: 0.5}
sess = tf.Session()
sess.run(soft_z, feed_dict)

array([-2.5, -2.2, -1.9, -1.6, -1.3, -1. , -0.7, -0.4, -0.1, -0. ,  0. ,
        0. ,  0.1,  0.4,  0.7,  1. ,  1.3,  1.6,  1.9,  2.2,  2.5])

In [15]:
#feed_dict = {z: np.linspace(-3., 3., 21, dtype=np.float32), th: 0.5}
feed_dict = {z: np.linspace(-3., 3., 21, dtype=np.float32), th: np.ones(21)*0.5}
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  v_soft_z = sess.run(soft_z, feed_dict)
  print(v_soft_z)
  grads = sess.run(g, feed_dict)
  print(grads)

[-2.5        -2.20000005 -1.9000001  -1.5999999  -1.29999995 -1.
 -0.70000005 -0.39999998 -0.10000002 -0.          0.          0.
  0.10000002  0.39999998  0.70000005  1.          1.29999995  1.5999999
  1.9000001   2.20000005  2.5       ]
[array([1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1.]), array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  0., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1.])]


## 例3. 行列の計算

1×2,2×1の行列を定義する

In [0]:
matrix1 = tf.constant([[3., 3.],[2., 2.]])
matrix2 = tf.constant([[2.],[2.]])

In [0]:
product = tf.matmul(matrix1, matrix2)

In [0]:
with tf.Session() as sess:
    result = sess.run(product)
print(result)

[[12.]
 [ 8.]]


In [0]:
type(result)



numpy.ndarray

In [0]:
inverse = tf.matrix_inverse(a)

In [0]:
mat = tf.matmul(inverse, b)

In [0]:
with tf.Session() as sess:
  result = sess.run(mat)
  print(result)

[[2.]
 [1.]]


問題　連立方程式

x+y+z=0
2x+y+3z+-5
-x+3x-z=8

In [0]:
mtr1 = tf.placeholder(tf.float32, shape=(3,3))
mtr2 = tf.placeholder(tf.float32, shape=(3,1))

In [0]:
inverse = tf.matrix_inverse(mtr1)
mat = tf.matmul(inverse,mtr2)

In [0]:
with tf.Session() as sess:
  result = sess.run(mat, feed_dict={mtr1:[[1.,1.,1.],[2.,1.,3.],[-1.,3.,-1.]], mtr2:[[0.],[-5.],[8.]]})
  print(result)

[[ 1.]
 [ 2.]
 [-3.]]
